analyze_query_task:
  description: >
    Analyze the user's query about O-RAN network performance. Identify what they want to know about the network.
    
    Specifically:
    1. What network metrics or information are they interested in? (cell load, user connections, signal quality, etc.)
    2. Which specific step or time period are they asking abo ut?
    3. Are they asking about specific cells or users?
    
    Formulate a clear, specific question for the Data Analyst.
    
    The user query is: {query}
  expected_output: >
    A clear, specific question for the Data Analyst that identifies:
    1. The specific metrics or data needed
    2. The step number
    3. Any specific cells or UEs mentioned
  agent: query_analyzer

analyze_data_task:
  description: >
    Use the DirectoryReadTool and CsvReaderTool to analyze O-RAN network data based on the query requirements.

    You'll receive the output from the Query Analyzer task, which contains a clear question about
    the network metrics to analyze. Use this analysis to guide your file selection and data examination.
    
    Analysis Process:
    1. Use DirectoryReadTool to identify available data files
    2. Select the relevant files based on:
       - File type (ue_reports for user data, cell_reports for cell data)
       - Step number mentioned in the query
    3. Use CsvQueryTool to extract and filter data with appropriate pandas queries
      - Construct queries that precisely match the requested metrics
      - Use multiple queries if needed to get complete results
    
    CRITICAL FIELD MATCHING RULES:
    - nrCellIdentity: The cell ID that the UE is ACTIVELY CONNECTED TO
    - nbCellIdentity_X: Neighboring cells that are DETECTED but NOT CONNECTED TO
    - Pay extremely close attention to field names and follow the O-RAN Network Metrics Guide precisely
    - ALL metrics in the O-RAN Metrics Guide should be considered for filtering based on the query
    
    Be thorough in your analysis and provide specific data from the O-RAN logs that directly
    answers the query. Include relevant metrics and their values.
  expected_output: >
   Detailed findings from the O-RAN data, including specific metrics,
    values, and any relevant context about the network performance.
    Ensure you report ALL matching findings, NOT just a sample
  agent: data_analyst
  context: [analyze_query_task]

formulate_response_task:
  description: >
    Create a clear, concise response that answers the user's original question about the O-RAN network.

    You have two key inputs for this task:
    1. The original user query: {query}
    2. The detailed findings from the Data Analyst task, which contains metrics, values, and context about the O-RAN network data.
    
    Your response should:
    1. Directly answer the user's question
    2. Shortly explain any technical terms in simple language
    3. Provide context about why the information is important
    4. Be concise and easy to understand
    
    Remember to reference both the user's original intent from their query and the specific data findings from the analysis.
  expected_output: >
    A clear, concise and short response that directly answers the user's question about
    the O-RAN network in easy-to-understand language.
  agent: response_formulator
  context: [analyze_data_task]